---
apiVersion: v1
kind: Service
metadata:
  name: microdonut
  labels:
    app: microdonut
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  microdonut_mapping
      prefix: /microdonut/
      service: microdonut:10001
spec:
  type: ClusterIP
  selector:
    app: microdonut
  ports:
  - protocol: TCP
    port: 10001
    name: http

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: microdonut
  labels:
    app: microdonut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microdonut
  template:
    metadata:
      labels:
        app: microdonut
    spec:
      containers:
      - name: microdonut
        image: danielbryantuk/microdonut:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 10001
        livenessProbe:
          httpGet:
            path: /
            port: 10001
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: tracing-config
